### PR TITLE
[Proposal] Allow request settings to be changed

### PR DESCRIPTION
**Pull request by bs1180**
Great tool! I need to include an Authorization header (with a bearer token) in my requests, which means accessing the request object. This PR provides the ability to set and remove headers using standard redux actions, as well as change the endpoint. The new settings are kept in the relateReducer.

This is a WIP - if you're happy with the proposal, I'll add some tests and tidy it up.

### CODE REVIEW

**Comment by bruno12mota** [comment]
Hey Ben! Awesome PR. Was in my plans to include a way to do that indeed. I agree with a way of manipulating headers through redux actions. 

Just an improvement I would suggest then would be wrap the reducer in a function to set the initial settings. I think an often case will be that one might want to only change the endpoint, so instead of having to call an action for that somewhere in the App, they can simply pass an initial state. Something along these:

```js
export default function (initialSettings) {
   const defaultSettings = {...};
   const defaultState = {
      settings: merge({}, defaultSettings, initialSettings)
   };
   // reducer code ....
}
```

So the dev wouldn't have to worry about it no more and more advanced cases can still change the headers anywhere.

With these we could also drop the defaults in other places and maintain them in one place.

Let me know what you think. Thanks for supporting by the way :smile:

**Comment by bs1180** [comment]
Great - I'll add that and resubmit :)

**Comment by bruno12mota** [comment]
Awesome, thanks! Will keep a close eye on it

**Comment by bruno12mota** [comment]
Added some better eslint rules for the project extended from [airbnb one](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb). Would be great if you pulled the project so it all gets standardized

**Comment by bruno12mota** [comment]
Hey @bs1180 how's the progress on it?

**Comment by bruno12mota** [comment]
I'll pick this up now if that's ok. Also needing the ability to define another endpoint.

**Comment by bs1180** [comment]
Shit, sorry, completely failed to get back to this. I didn't get round to updating this, but I can do if you would like?

**Comment by bruno12mota** [comment]
No worries, going through it now :smiley:

**Comment by bs1180** [comment]
Ok - sorry for being tardy :-1:

**Comment by bruno12mota** [comment]
No worries. Much of the work was from your part :wink: 

It is now pushed and published to npm

Cheers!

**Pull request closed without merging**
